kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: opencryptoki-token-pvc
spec: 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 1Gi 
  storageClassName: nfs